# Generated by Django 2.1.5 on 2020-03-02 05:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_automation'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Automation',
        ),
        migrations.RemoveField(
            model_name='blog',
            name='image',
        ),
        migrations.RemoveField(
            model_name='blog',
            name='pub_date',
        ),
    ]
